version: '3.7'
services:
    zookeeper:
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zookeeper:2888:3888
        image: zookeeper:3.4.9
        volumes:
            - ./logs/zoo/data:/data
            - ./logs/zoo/datalog:/datalog

    kafka:
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://127.0.0.1:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        image: confluentinc/cp-kafka:5.5.1
        ports:
            - 9092:9092
        volumes:
            - ./logs/kafka/data:/var/lib/kafka/data

    publisher:
        build:
            context: .
            dockerfile: Dockerfile
        command: src/publisher.py
        depends_on:
            - kafka
        environment:
            BOOTSTRAP_SERVER: kafka:19092
            TOPIC_NAME: weather
        restart: on-failure

    subscriber:
        build:
            context: .
            dockerfile: Dockerfile
        command: src/subscriber.py
        depends_on:
            - kafka
        environment:
            BOOTSTRAP_SERVER: kafka:19092
            TOPIC_NAME: weather
        restart: on-failure
